"""esquema inicial

Revision ID: 3da047b8123c
Revises: 
Create Date: 2026-09-08 13:58:56.648520+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_post',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('body_md_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_post')),
    sa.UniqueConstraint('slug', name=op.f('uq_blog_post_slug'))
    )
    op.create_index(op.f('ix_blog_post_deleted_at'), 'blog_post', ['deleted_at'], unique=False)
    op.create_table('jurisdiction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['jurisdiction.id'], name=op.f('fk_jurisdiction_parent_id_jurisdiction')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jurisdiction')),
    sa.UniqueConstraint('code', name=op.f('uq_jurisdiction_code'))
    )
    op.create_index(op.f('ix_jurisdiction_country_code'), 'jurisdiction', ['country_code'], unique=False)
    op.create_index(op.f('ix_jurisdiction_parent_id'), 'jurisdiction', ['parent_id'], unique=False)
    op.create_table('plan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price_monthly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_yearly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'EUR'"), nullable=False),
    sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan')),
    sa.UniqueConstraint('code', name=op.f('uq_plan_code'))
    )
    op.create_table('organization',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('vat_number', sa.String(length=32), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('billing_email', sa.String(length=320), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('subscription_status', sa.String(length=32), server_default=sa.text("'TRIALING'"), nullable=False),
    sa.Column('payment_provider', sa.String(length=32), nullable=True),
    sa.Column('payment_customer_id', sa.String(length=128), nullable=True),
    sa.Column('payment_subscription_id', sa.String(length=128), nullable=True),
    sa.Column('trial_plan_id', sa.UUID(), nullable=True),
    sa.Column('trial_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_extension_days', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('trial_extended_by_user_id', sa.UUID(), nullable=True),
    sa.Column('has_used_trial', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('signup_email_domain', sa.String(length=255), nullable=True),
    sa.Column('signup_ip', postgresql.INET(), nullable=True),
    sa.Column('is_internal', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], name=op.f('fk_organization_plan_id_plan')),
    sa.ForeignKeyConstraint(['trial_plan_id'], ['plan.id'], name=op.f('fk_organization_trial_plan_id_plan')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization'))
    )
    op.create_index(op.f('ix_organization_deleted_at'), 'organization', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_organization_signup_email_domain'), 'organization', ['signup_email_domain'], unique=False)
    op.create_index(op.f('ix_organization_signup_ip'), 'organization', ['signup_ip'], unique=False)
    op.create_index(op.f('ix_organization_subscription_status'), 'organization', ['subscription_status'], unique=False)
    op.create_index(op.f('ix_organization_trial_ends_at'), 'organization', ['trial_ends_at'], unique=False)
    op.create_table('trial_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('duration_days', sa.Integer(), server_default=sa.text('14'), nullable=False),
    sa.Column('trial_plan_code', sa.String(length=32), server_default=sa.text("'PRO'"), nullable=False),
    sa.Column('requires_card', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('fallback_plan_code', sa.String(length=32), server_default=sa.text("'FREE'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_days > 0', name=op.f('ck_trial_config_duration_is_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trial_config'))
    )
    op.create_index('uq_trial_config_singleton', 'trial_config', [sa.literal_column('(true)')], unique=True)
    op.create_table('user_account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('locale', sa.String(length=5), server_default=sa.text("'es'"), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default=sa.text("'Europe/Madrid'"), nullable=False),
    sa.Column('role', sa.String(length=32), server_default=sa.text("'MEMBER'"), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_secret', sa.Text(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_user_account_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_account')),
    sa.UniqueConstraint('email', name=op.f('uq_user_account_email'))
    )
    op.create_index(op.f('ix_user_account_deleted_at'), 'user_account', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_user_account_organization_id'), 'user_account', ['organization_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user_account.id'], name=op.f('fk_audit_log_actor_user_id_user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_log_entity_type_entity_id', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_table('invitation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=32), server_default=sa.text("'MEMBER'"), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_invitation_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitation')),
    sa.UniqueConstraint('token', name=op.f('uq_invitation_token'))
    )
    op.create_index('ix_invitation_organization_id_email', 'invitation', ['organization_id', 'email'], unique=False)
    op.create_table('notification_preference',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('digest_frequency', sa.String(length=32), server_default=sa.text("'DAILY'"), nullable=False),
    sa.Column('digest_hour', sa.Integer(), server_default=sa.text('8'), nullable=False),
    sa.Column('digest_weekday', sa.Integer(), nullable=True),
    sa.Column('blocking_bypasses_digest', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('digest_hour BETWEEN 0 AND 23', name=op.f('ck_notification_preference_digest_hour_in_range')),
    sa.CheckConstraint('digest_weekday IS NULL OR digest_weekday BETWEEN 0 AND 6', name=op.f('ck_notification_preference_digest_weekday_in_range')),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_notification_preference_user_id_user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_preference')),
    sa.UniqueConstraint('user_id', name=op.f('uq_notification_preference_user_id'))
    )
    op.create_table('regulation_family',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jurisdiction_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('authority', sa.String(length=120), nullable=True),
    sa.Column('official_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdiction.id'], name=op.f('fk_regulation_family_jurisdiction_id_jurisdiction')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regulation_family'))
    )
    op.create_index('uq_regulation_family_jurisdiction_id_code', 'regulation_family', ['jurisdiction_id', 'code'], unique=True)
    op.create_table('webhook_endpoint',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('secret', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_webhook_endpoint_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_endpoint'))
    )
    op.create_index(op.f('ix_webhook_endpoint_organization_id'), 'webhook_endpoint', ['organization_id'], unique=False)
    op.create_table('document_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('regulation_family_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['regulation_family_id'], ['regulation_family.id'], name=op.f('fk_document_type_regulation_family_id_regulation_family')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_type'))
    )
    op.create_index('uq_document_type_regulation_family_id_code', 'document_type', ['regulation_family_id', 'code'], unique=True)
    op.create_table('source',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('regulation_family_id', sa.UUID(), nullable=False),
    sa.Column('document_type_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('collector_type', sa.String(length=32), nullable=False),
    sa.Column('collector_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('check_frequency', sa.String(length=64), nullable=False),
    sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.String(length=32), server_default=sa.text("'WARM'"), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_type.id'], name=op.f('fk_source_document_type_id_document_type')),
    sa.ForeignKeyConstraint(['regulation_family_id'], ['regulation_family.id'], name=op.f('fk_source_regulation_family_id_regulation_family')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source'))
    )
    op.create_index(op.f('ix_source_deleted_at'), 'source', ['deleted_at'], unique=False)
    op.create_index('ix_source_next_check_at_due', 'source', ['next_check_at'], unique=False, postgresql_where=sa.text('is_active AND deleted_at IS NULL'))
    op.create_index('ix_source_regulation_family_id', 'source', ['regulation_family_id'], unique=False)
    op.create_table('alert_subscription',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scope_type', sa.String(length=32), nullable=False),
    sa.Column('jurisdiction_id', sa.UUID(), nullable=True),
    sa.Column('regulation_family_id', sa.UUID(), nullable=True),
    sa.Column('document_type_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('min_severity', sa.String(length=32), server_default=sa.text("'INFO'"), nullable=False),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"email": true}\'::jsonb'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('inactive_reason', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('num_nonnulls(jurisdiction_id, regulation_family_id, document_type_id, source_id) = 1', name=op.f('ck_alert_subscription_exactly_one_scope')),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_type.id'], name=op.f('fk_alert_subscription_document_type_id_document_type')),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdiction.id'], name=op.f('fk_alert_subscription_jurisdiction_id_jurisdiction')),
    sa.ForeignKeyConstraint(['regulation_family_id'], ['regulation_family.id'], name=op.f('fk_alert_subscription_regulation_family_id_regulation_family')),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_alert_subscription_source_id_source')),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_alert_subscription_user_id_user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_subscription'))
    )
    op.create_index(op.f('ix_alert_subscription_deleted_at'), 'alert_subscription', ['deleted_at'], unique=False)
    op.create_index('ix_alert_subscription_user_id_active', 'alert_subscription', ['user_id'], unique=False, postgresql_where=sa.text('is_active'))
    op.create_table('artifact',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=160), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=True),
    sa.Column('fetched_url', sa.Text(), nullable=False),
    sa.Column('declared_version', sa.String(length=64), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('http_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(content_hash) = 64', name=op.f('ck_artifact_content_hash_is_sha256')),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_artifact_source_id_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifact'))
    )
    op.create_index('ix_artifact_source_id_captured_at', 'artifact', ['source_id', sa.literal_column('captured_at DESC')], unique=False)
    op.create_index('uq_artifact_source_id_content_hash', 'artifact', ['source_id', 'content_hash'], unique=True)
    op.create_table('pipeline_incident',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_pipeline_incident_source_id_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_incident'))
    )
    op.create_index('ix_pipeline_incident_open', 'pipeline_incident', ['source_id'], unique=False, postgresql_where=sa.text('resolved_at IS NULL'))
    op.create_table('change_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('artifact_from_id', sa.UUID(), nullable=True),
    sa.Column('artifact_to_id', sa.UUID(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('structural_diff', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('diff_schema_version', sa.String(length=32), nullable=False),
    sa.Column('severity_suggested', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'DETECTED'"), nullable=False),
    sa.Column('discard_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'DISCARDED' OR discard_reason IS NOT NULL", name=op.f('ck_change_event_discard_needs_a_reason')),
    sa.ForeignKeyConstraint(['artifact_from_id'], ['artifact.id'], name=op.f('fk_change_event_artifact_from_id_artifact')),
    sa.ForeignKeyConstraint(['artifact_to_id'], ['artifact.id'], name=op.f('fk_change_event_artifact_to_id_artifact')),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_change_event_source_id_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_event'))
    )
    op.create_index('ix_change_event_detected_at_pending', 'change_event', ['detected_at'], unique=False, postgresql_where=sa.text("status = 'DETECTED'"))
    op.create_index(op.f('ix_change_event_source_id'), 'change_event', ['source_id'], unique=False)
    op.create_index('uq_change_event_artifact_from_id_artifact_to_id', 'change_event', ['artifact_from_id', 'artifact_to_id'], unique=True)
    op.create_table('normalized_form',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('form_type', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parser_version', sa.String(length=32), nullable=False),
    sa.Column('is_partial', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('parse_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('inner_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifact.id'], name=op.f('fk_normalized_form_artifact_id_artifact')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_normalized_form'))
    )
    op.create_index('uq_normalized_form_artifact_id_form_type_parser_version', 'normalized_form', ['artifact_id', 'form_type', 'parser_version'], unique=True)
    op.create_table('change_note',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('change_event_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'DETECTED'"), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('title_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('impact_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_required_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('effective_date_note', sa.Text(), nullable=True),
    sa.Column('affected_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('xml_example_before', sa.Text(), nullable=True),
    sa.Column('xml_example_after', sa.Text(), nullable=True),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('llm_draft', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'PUBLISHED' OR (reviewed_by_user_id IS NOT NULL AND reviewed_at IS NOT NULL AND published_at IS NOT NULL)", name=op.f('ck_change_note_publication_requires_human_review')),
    sa.ForeignKeyConstraint(['change_event_id'], ['change_event.id'], name=op.f('fk_change_note_change_event_id_change_event')),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['user_account.id'], name=op.f('fk_change_note_reviewed_by_user_id_user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_note')),
    sa.UniqueConstraint('change_event_id', name=op.f('uq_change_note_change_event_id'))
    )
    op.create_index(op.f('ix_change_note_effective_date'), 'change_note', ['effective_date'], unique=False)
    op.create_index('ix_change_note_published_at_public', 'change_note', [sa.literal_column('published_at DESC')], unique=False, postgresql_where=sa.text("status = 'PUBLISHED' AND is_public"))
    op.create_index(op.f('ix_change_note_severity'), 'change_note', ['severity'], unique=False)
    op.create_index(op.f('ix_change_note_status'), 'change_note', ['status'], unique=False)
    op.create_table('notification_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('change_note_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'QUEUED'"), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['change_note_id'], ['change_note.id'], name=op.f('fk_notification_log_change_note_id_change_note')),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_notification_log_user_id_user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_log'))
    )
    op.create_index('uq_notification_log_user_id_change_note_id_channel', 'notification_log', ['user_id', 'change_note_id', 'channel'], unique=True)
    # ### end Alembic commands ###

    # La FK organization -> user_account se crea aparte porque es circular:
    # user_account.organization_id apunta de vuelta. DEFERRABLE INITIALLY DEFERRED
    # permite insertar la organizacion y su primer usuario en la misma transaccion.
    op.create_foreign_key(
        op.f("fk_organization_trial_extended_by_user_id_user_account"),
        "organization",
        "user_account",
        ["trial_extended_by_user_id"],
        ["id"],
        deferrable=True,
        initially="DEFERRED",
    )


def downgrade() -> None:
    op.drop_constraint(
        op.f("fk_organization_trial_extended_by_user_id_user_account"),
        "organization",
        type_="foreignkey",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_notification_log_user_id_change_note_id_channel', table_name='notification_log')
    op.drop_table('notification_log')
    op.drop_index(op.f('ix_change_note_status'), table_name='change_note')
    op.drop_index(op.f('ix_change_note_severity'), table_name='change_note')
    op.drop_index('ix_change_note_published_at_public', table_name='change_note', postgresql_where=sa.text("status = 'PUBLISHED' AND is_public"))
    op.drop_index(op.f('ix_change_note_effective_date'), table_name='change_note')
    op.drop_table('change_note')
    op.drop_index('uq_normalized_form_artifact_id_form_type_parser_version', table_name='normalized_form')
    op.drop_table('normalized_form')
    op.drop_index('uq_change_event_artifact_from_id_artifact_to_id', table_name='change_event')
    op.drop_index(op.f('ix_change_event_source_id'), table_name='change_event')
    op.drop_index('ix_change_event_detected_at_pending', table_name='change_event', postgresql_where=sa.text("status = 'DETECTED'"))
    op.drop_table('change_event')
    op.drop_index('ix_pipeline_incident_open', table_name='pipeline_incident', postgresql_where=sa.text('resolved_at IS NULL'))
    op.drop_table('pipeline_incident')
    op.drop_index('uq_artifact_source_id_content_hash', table_name='artifact')
    op.drop_index('ix_artifact_source_id_captured_at', table_name='artifact')
    op.drop_table('artifact')
    op.drop_index('ix_alert_subscription_user_id_active', table_name='alert_subscription', postgresql_where=sa.text('is_active'))
    op.drop_index(op.f('ix_alert_subscription_deleted_at'), table_name='alert_subscription')
    op.drop_table('alert_subscription')
    op.drop_index('ix_source_regulation_family_id', table_name='source')
    op.drop_index('ix_source_next_check_at_due', table_name='source', postgresql_where=sa.text('is_active AND deleted_at IS NULL'))
    op.drop_index(op.f('ix_source_deleted_at'), table_name='source')
    op.drop_table('source')
    op.drop_index('uq_document_type_regulation_family_id_code', table_name='document_type')
    op.drop_table('document_type')
    op.drop_index(op.f('ix_webhook_endpoint_organization_id'), table_name='webhook_endpoint')
    op.drop_table('webhook_endpoint')
    op.drop_index('uq_regulation_family_jurisdiction_id_code', table_name='regulation_family')
    op.drop_table('regulation_family')
    op.drop_table('notification_preference')
    op.drop_index('ix_invitation_organization_id_email', table_name='invitation')
    op.drop_table('invitation')
    op.drop_index('ix_audit_log_entity_type_entity_id', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_user_account_organization_id'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_deleted_at'), table_name='user_account')
    op.drop_table('user_account')
    op.drop_index('uq_trial_config_singleton', table_name='trial_config')
    op.drop_table('trial_config')
    op.drop_index(op.f('ix_organization_trial_ends_at'), table_name='organization')
    op.drop_index(op.f('ix_organization_subscription_status'), table_name='organization')
    op.drop_index(op.f('ix_organization_signup_ip'), table_name='organization')
    op.drop_index(op.f('ix_organization_signup_email_domain'), table_name='organization')
    op.drop_index(op.f('ix_organization_deleted_at'), table_name='organization')
    op.drop_table('organization')
    op.drop_table('plan')
    op.drop_index(op.f('ix_jurisdiction_parent_id'), table_name='jurisdiction')
    op.drop_index(op.f('ix_jurisdiction_country_code'), table_name='jurisdiction')
    op.drop_table('jurisdiction')
    op.drop_index(op.f('ix_blog_post_deleted_at'), table_name='blog_post')
    op.drop_table('blog_post')
    # ### end Alembic commands ###
